# Generated by Django 3.1.5 on 2021-02-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('1', '男'), ('2', '女')], default=('1', '男'), max_length=5, verbose_name='性别'),
        ),
    ]
